'use strict';
const CFG={ csv:'data/basededatosrm08cc.csv', geo:'data/indicemantenimiento.json', f:{alcaldia:'alcaldia',nivel:'principal',nombre:'inmueble',indice:'Indice_Man',ccts:['cct1','cct2','cct3','cct4']}, maintenance:['impermeabi','interior','exterior1','loseta','ventanas','ventanas1','ventanas2','puertas','escaleras','pluviales','techos','desazolve','deterioro','concreto','tinacos','cisterna','agua','agua1','hidrosanit','sanitarios','luminarias','electrica','transforma','lamina']};
function idx(p){const v=Number(p[CFG.f.indice]);return Number.isFinite(v)?v:CFG.maintenance.reduce((a,k)=>a+(Number(p[k])===1?1:0),0)}
function cls(v){if(v<=6)return'Muy baja';if(v<=10)return'Baja';if(v<=14)return'Media';if(v<=18)return'Alta';return'Muy alta'}
async function load(){let rows=[];try{const g=await fetch(CFG.geo,{cache:'no-store'}).then(r=>r.json());if(g.features?.length)rows=g.features.map(f=>f.properties||{})}catch(e){}if(!rows.length){const t=await fetch(CFG.csv,{cache:'no-store'}).then(r=>r.text());rows=Papa.parse(t,{header:true,skipEmptyLines:true}).data}return rows.map(p=>({...p,_indice:idx(p),_clase:cls(idx(p))}))}
function group(rows,field){const m=new Map();rows.forEach(r=>{const k=String(r[field]||'Sin dato').trim()||'Sin dato';if(!m.has(k))m.set(k,[]);m.get(k).push(r)});return [...m.entries()].map(([k,a])=>({k,n:a.length,prom:avg(a.map(x=>x._indice)),max:Math.max(...a.map(x=>x._indice)),min:Math.min(...a.map(x=>x._indice))})).sort((a,b)=>b.prom-a.prom)}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:0}function fmt(v){return Number(v).toFixed(1)}function ccts(r){return CFG.f.ccts.map(k=>r[k]).filter(Boolean).join(', ')}
function renderTable(id,heads,rows){document.getElementById(id).innerHTML='<thead><tr>'+heads.map(h=>`<th>${h}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(c=>`<td>${c}</td>`).join('')+'</tr>').join('')+'</tbody>'}
load().then(rows=>{const vals=rows.map(r=>r._indice);document.getElementById('total').textContent=rows.length.toLocaleString('es-MX');document.getElementById('promedio').textContent=fmt(avg(vals));document.getElementById('maximo').textContent=Math.max(...vals);document.getElementById('minimo').textContent=Math.min(...vals);
const order=['Muy baja','Baja','Media','Alta','Muy alta'];renderTable('tablaClasificacion',['Clasificación','Escuelas','Porcentaje'],order.map(k=>{const n=rows.filter(r=>r._clase===k).length;return[k,n,fmt(n*100/rows.length)+'%']}));
renderTable('tablaNivel',['Nivel','Escuelas','Promedio','Máx.','Mín.'],group(rows,CFG.f.nivel).map(g=>[g.k,g.n,fmt(g.prom),g.max,g.min]));
renderTable('tablaAlcaldia',['Alcaldía','Escuelas','Promedio','Máx.','Mín.'],group(rows,CFG.f.alcaldia).map(g=>[g.k,g.n,fmt(g.prom),g.max,g.min]));
renderTable('tablaRanking',['Lugar','Escuela','CCT','Alcaldía','Nivel','Índice','Clasificación'],rows.sort((a,b)=>b._indice-a._indice).slice(0,30).map((r,i)=>[i+1,r[CFG.f.nombre]||'Sin nombre',ccts(r)||'N/D',r[CFG.f.alcaldia]||'N/D',r[CFG.f.nivel]||'N/D',r._indice,r._clase]));
}).catch(e=>{console.error(e);alert('No se pudieron cargar las estadísticas.');});
